server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro-rating
    username: root
    password: Shubham3417@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true